"""Environment type definitions.

The EnvironmentType enum is the single canonical identifier that drives
trajectory generation mode selection.  Configs may still express the same
choice with the ``has_policy`` / ``has_user_agent`` booleans; ``from_config``
maps those onto the enum.

The three types differ along two axes — whether a simulated user drives the
conversation, and whether the assistant is held to a written policy:

  TOOLS_ONLY           no user simulation, no policy
  WITH_USER            user simulation, no policy
  WITH_USER_AND_POLICY user simulation plus domain policy
"""

from enum import Enum


class EnvironmentType(str, Enum):
    """Canonical environment type that drives trajectory generation behavior."""

    TOOLS_ONLY = "tools_only"
    """Static environment: no user agent, no policy.
    Trajectory is generated by the assistant alone responding to a fixed query.
    Use this when you are training tool selection and argument construction and the
    conversation itself is not the object of study. See `configs/quickstart.yaml`.
    """

    WITH_USER_AND_POLICY = "with_user_and_policy"
    """Dynamic environment with domain policy.
    A simulated user agent drives the conversation; the assistant must follow policy rules.
    Requires `policy_rules` text on the category — a category that carries it is treated as
    this type even when the environment default is TOOLS_ONLY. See `configs/hotel_policy.yaml`.
    """

    WITH_USER = "with_user"
    """Dynamic environment without policy.
    A simulated user agent drives the conversation; no explicit policy rules are enforced.
    Use this for multi-turn behaviour — clarification, follow-ups, changes of mind — where
    there is no policy for the assistant to comply with.
    """

    # ── Properties ────────────────────────────────────────────────────────

    @property
    def has_user_agent(self) -> bool:
        """Whether trajectory generation uses a simulated user agent."""
        return self in (
            EnvironmentType.WITH_USER_AND_POLICY,
            EnvironmentType.WITH_USER,
        )

    @property
    def has_policy(self) -> bool:
        """Whether categories are expected to carry domain policy / rules text."""
        return self is EnvironmentType.WITH_USER_AND_POLICY

    @property
    def environment_type(self) -> str:
        """Default trajectory mode string used by generate_trajectories steps.

        Returns:
            "tools_only"           for TOOLS_ONLY
            "with_user_and_policy"          for WITH_USER_AND_POLICY
            "with_user" for WITH_USER
        """
        if self is EnvironmentType.TOOLS_ONLY:
            return "tools_only"
        if self is EnvironmentType.WITH_USER_AND_POLICY:
            return "with_user_and_policy"
        return "with_user"

    # ── Factory ───────────────────────────────────────────────────────────

    @classmethod
    def from_config(cls, config: dict) -> "EnvironmentType":
        """Infer EnvironmentType from a config dict.

        Lookup priority:
        1. Explicit ``environment_type`` key (string value of the enum).
        2. The boolean flags ``has_user_agent`` / ``has_policy``.

        Args:
            config: Environment or benchmark config dict.

        Returns:
            The matching EnvironmentType.

        Raises:
            ValueError: If ``environment_type`` is present but not a valid value.
        """
        explicit = config.get("environment_type")
        if explicit is not None:
            try:
                return cls(explicit)
            except ValueError:
                valid = [e.value for e in cls]
                raise ValueError(
                    f"Unknown environment_type: {explicit!r}. Valid values: {valid}"
                )

        # Infer from the boolean flags
        has_user_agent = config.get("has_user_agent", False)
        has_policy = config.get("has_policy", False)

        if has_user_agent and has_policy:
            return cls.WITH_USER_AND_POLICY
        if has_user_agent:
            return cls.WITH_USER
        return cls.TOOLS_ONLY
